---
- name: Get Hostgroups 
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Hostgroups | Get Basic Info
      ansible.builtin.uri:
        url: "{{ satellite_url }}/api/hostgroups"
        method: GET
        user: "{{ satellite_username }}"
        password: "{{ satellite_passwd }}"
        force_basic_auth: true
        validate_certs: false
        return_content: true
      register: all_hostgroups

    - name: Hostgroups | Get Detailed Info
      ansible.builtin.uri:
        url: "{{ satellite_url }}/api/hostgroups/{{ item.id }}"
        method: GET
        user: "{{ satellite_username }}"
        password: "{{ satellite_passwd }}"
        force_basic_auth: true
        validate_certs: false
        return_content: true
      loop: "{{ all_hostgroups.json.results }}"
      register: result_hostgroups_info
  
    - name: Subnets | Template Out Results
      ansible.builtin.template:
        src: templates/hostgroups.yml.j2
        dest: configs/hostgroups.yml
        owner: "{{ template_owner }}"
        group: "{{ template_group }}"
        mode: "{{ template_mode }}"
