---
# defaults file for dispatch
- name: Manage Satellite Settings
  ansible.builtin.include_tasks: satellite_settings.yaml
  args:
    apply:
      tags: settings
  tags: settings

- name: Manage LDAP Authentication
  ansible.builtin.include_tasks: satellite_auth_sources_ldap.yaml
  args:
    apply:
      tags: auth_sources_ldap
  tags: auth_sources_ldap

- name: Manage User Groups
  ansible.builtin.include_tasks: satellite_usergroups.yaml
  args:
    apply:
      tags: usergroups
  tags: usergroups

- name: Create Organizations
  ansible.builtin.include_tasks: satellite_organizations.yaml
  args:
    apply:
      tags: organizations
  tags: organizations

- name: Manage Locations
  ansible.builtin.include_tasks: satellite_locations.yaml
  args:
    apply:
      tags: locations
  tags: locations

- name: Manage Lifecycle Environments
  ansible.builtin.include_tasks: satellite_lifecycle_environments.yaml
  args:
    apply:
      tags: lifecycle_environments
  tags: lifecycle_environments

- name: Manage Repository Sets
  ansible.builtin.include_tasks: satellite_repository_sets.yaml
  args:
    apply:
      tags: repository_sets
  tags: repository_sets

- name: Manage Repositories
  ansible.builtin.include_tasks: satellite_repositories.yaml
  args:
    apply:
      tags: repositories
  tags: repositories

- name: Manage Sync Plans
  ansible.builtin.include_tasks: satellite_sync_plans.yaml
  args:
    apply:
      tags: sync_plans
  tags: sync_plans

- name: Manage Content Views
  ansible.builtin.include_tasks: satellite_content_views.yaml
  args:
    apply:
      tags: content_views
  tags: content_views

# Don't treat this appart from Content Views by now
# - name: Manage Content Views Filters
#   ansible.builtin.include_tasks: satellite_content_view_filters.yaml
#   args:
#     apply:
#       tags: content_view_filters
#   tags: content_view_filters
# Don't treat this appart from Content Views by now

- name: Publish and Promote Content Views
  when: false
  ansible.builtin.include_tasks: satellite_cv_versions.yaml
  args:
    apply:
      tags: cv_publish_promote
  tags: cv_publish_promote

- name: Manage Activation Keys
  ansible.builtin.include_tasks: satellite_activation_keys.yaml
  args:
    apply:
      tags: activation_keys
  tags: activation_keys

- name: Manage Host Collections
  ansible.builtin.include_tasks: satellite_host_collections.yaml
  args:
    apply:
      tags: host_collections
  tags: host_collections

- name: Create Products
  ansible.builtin.include_tasks: satellite_products.yaml
  args:
    apply:
      tags: products
  tags: products

- name: Create Content Credentials
  ansible.builtin.include_tasks: satellite_content_credentials.yaml
  args:
    apply:
      tags: content_credentials
  tags: content_credentials

- name: Create Partition Tables
  ansible.builtin.include_tasks: satellite_partition_tables.yaml
  args:
    apply:
      tags: partition_tables
  tags: partition_tables

- name: Create Provisioning Templates
  ansible.builtin.include_tasks: satellite_provisioning_templates.yaml
  args:
    apply:
      tags: provisioning_templates
  tags: provisioning_templates

- name: Create OperatingSystems
  ansible.builtin.include_tasks: satellite_operatingsystems.yaml
  args:
    apply:
      tags: operatingsystems
  tags: operatingsystems
...
